// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKZSqCjfOsT1LfvxWeFbueG8_NOkcZJb8',
    appId: '1:491279298066:web:c80ad361f6c5e6cdeaf2cb',
    messagingSenderId: '491279298066',
    projectId: 'english-training-app-679de',
    authDomain: 'english-training-app-679de.firebaseapp.com',
    databaseURL: 'https://english-training-app-679de-default-rtdb.firebaseio.com',
    storageBucket: 'english-training-app-679de.firebasestorage.app',
    measurementId: 'G-CLJ8TP4NH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClydsd5vS-UPAHnspIAfYjNgvScliDIZE',
    appId: '1:491279298066:android:dcc866c6461dfcddeaf2cb',
    messagingSenderId: '491279298066',
    projectId: 'english-training-app-679de',
    databaseURL: 'https://english-training-app-679de-default-rtdb.firebaseio.com',
    storageBucket: 'english-training-app-679de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPfJo6Bx58c7Cd1yfsP4TPnmWT0k2IIsQ',
    appId: '1:491279298066:ios:ec0b7562517430a3eaf2cb',
    messagingSenderId: '491279298066',
    projectId: 'english-training-app-679de',
    databaseURL: 'https://english-training-app-679de-default-rtdb.firebaseio.com',
    storageBucket: 'english-training-app-679de.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPfJo6Bx58c7Cd1yfsP4TPnmWT0k2IIsQ',
    appId: '1:491279298066:ios:ec0b7562517430a3eaf2cb',
    messagingSenderId: '491279298066',
    projectId: 'english-training-app-679de',
    databaseURL: 'https://english-training-app-679de-default-rtdb.firebaseio.com',
    storageBucket: 'english-training-app-679de.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKZSqCjfOsT1LfvxWeFbueG8_NOkcZJb8',
    appId: '1:491279298066:web:b3dfd1ce02fe6571eaf2cb',
    messagingSenderId: '491279298066',
    projectId: 'english-training-app-679de',
    authDomain: 'english-training-app-679de.firebaseapp.com',
    databaseURL: 'https://english-training-app-679de-default-rtdb.firebaseio.com',
    storageBucket: 'english-training-app-679de.firebasestorage.app',
    measurementId: 'G-MENWY47T4G',
  );

}